USE [master]
GO

/****** Object:  Database [Datalake_AdWork]    Script Date: 10/04/2025 1:20:16 SA ******/
CREATE DATABASE [Datalake_AdWork]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Datalake_AdWork', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL_SERVER_2022\MSSQL\DATA\Datalake_AdWork.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Datalake_AdWork_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL_SERVER_2022\MSSQL\DATA\Datalake_AdWork_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Datalake_AdWork].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Datalake_AdWork] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET ARITHABORT OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Datalake_AdWork] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Datalake_AdWork] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Datalake_AdWork] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Datalake_AdWork] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET RECOVERY FULL 
GO

ALTER DATABASE [Datalake_AdWork] SET  MULTI_USER 
GO

ALTER DATABASE [Datalake_AdWork] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Datalake_AdWork] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Datalake_AdWork] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Datalake_AdWork] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Datalake_AdWork] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Datalake_AdWork] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Datalake_AdWork] SET QUERY_STORE = ON
GO

ALTER DATABASE [Datalake_AdWork] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Datalake_AdWork] SET  READ_WRITE 
GO

